### PR TITLE
chores(doc): add instruction for cloudflare ai gateway

### PR DESCRIPTION
**Pull request by zhwei**

### CODE REVIEW

**Comment by liby** [comment]
It feels like this type of information would be better written in REDAME.me, would you be interested?

**Comment by zhwei** [comment]
There are many configuration items missing in the README, so I think adding them here is more effective for users.

**Comment by liby** [comment]
Thanks again. I've already updated the documentation with detailed configuration information. Please feel free to add any additional content you think is necessary:
   - [Configuration Manual CN](https://github.com/openai-translator/bob-plugin-openai-translator/blob/main/docs/configuration_manual_CN.md)
   - [Configuration Manual EN](https://github.com/openai-translator/bob-plugin-openai-translator/blob/main/docs/configuration_manual_EN.md)

Moreover, updating the remark within the configuration options would require releasing a new version, which might introduce unnecessary noise for some users, especially if there are no functional improvements or bug fixes involved. I believe maintaining simplicity in the configuration options and handling detailed explanations through documentation strikes a better balance and serves our users more effectively.

**Comment by zhwei** [comment]
Thanks for your reply, that's a good point, i have updated to new doc file, review please.

**Review by liby — APPROVED** [review]

**Pull request merged**
