### PR TITLE
Fix bug for Azure OpenAI

### PR DESCRIPTION
**Pull request by mashihua**
Azure will send audit information to at first stream message like this:

```
data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"low"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[],"usage":null}
```

So, fix it.

### CODE REVIEW

**Comment by liby** [comment]
Thank you for your pull request to the [OpenAI Translator Bob Plugin](https://github.com/openai-translator/bob-plugin-openai-translator#openai-translator-bob-plugin).

I appreciate your effort to improve the project. However, to maintain the quality and coherence of contributions, it is important that all contributors adhere to the guidelines specified [contributing guidelines](https://github.com/openai-translator/bob-plugin-openai-translator/blob/main/.github/contributing.md), as well as follow the format provided by the ISSUE TEMPLATE.

Before we can proceed with your pull request, could you please take the following actions?

1. **Issue Creation**: Open an issue that describes the problem you've encountered. This will help us track the problem and the related solution more effectively.

2. **Format Adherence**: Ensure that your pull request description follows the format outlined in the [bug-report template](https://github.com/openai-translator/bob-plugin-openai-translator/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml). This should provide a clear understanding of the problem, steps to reproduce it, expected behavior, and any other relevant context.

3. Commit Message: Update your commit messages to adhere to the [Conventional Commits](https://www.conventionalcommits.org/en/) guidelines. This is crucial for automated tooling and readable history.

Additionally, since I am currently not using Azure OpenAI API and unable to verify the issue firsthand, and a preliminary documentation search didn't yield relevant details, I would require a more detailed context. This information is essential to understand the situation fully and address the issue appropriately.

Please provide the requested details at your earliest convenience. Your collaboration is crucial to keep the repository well-maintained and assistive for everyone.

**Comment by mashihua** [comment]
The picture show what is going on that use Azure OpenAI stream interface.


截屏2023-11-10 11 46 01

**Comment by liby** [comment]
Apologies, but could you please complete the steps for Format Adherence and Commit Message? 

Additionally, if possible, include the full response from the Azure OpenAI API, with sensitive information redacted, in the PR description. This would greatly help in saving time for both parties. Thank you.

**Comment by mashihua** [comment]
Sure, this is curl with full request and response:

```
curl --location 'https://jp-gpt.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-08-01-preview' \
--header 'Api-Key: $KEY' \
--header 'Content-Type: application/json' \
--data '{
"stream": true,
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Hello"
        }
    ]
}'


data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"role":"assistant"},"content_filter_results":{}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":"Hello"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":"!"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" How"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" can"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" I"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" assist"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" you"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":" today"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":null,"delta":{"content":"?"},"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"usage":null}

data: {"id":"chatcmpl-8JCRalX4mRuonXYDjiWdJofTF78Nr","object":"chat.completion.chunk","created":1699586758,"model":"gpt-35-turbo","choices":[{"index":0,"finish_reason":"stop","delta":{},"content_filter_results":{}}],"usage":null}

data: [DONE]
```

**Comment by liby** [comment]
#100

**Pull request closed without merging**
